"""add explanation difficulty topic to questions

Revision ID: 81d6158f037c
Revises: f6ba3d4af7b8
Create Date: 2025-08-31 22:16:07.219725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81d6158f037c'
down_revision: Union[str, Sequence[str], None] = 'f6ba3d4af7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('difficulty', sa.String(length=16), nullable=True))
    op.add_column('questions', sa.Column('topic', sa.String(length=128), nullable=True))
    op.alter_column('questions', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('questions', 'topic')
    op.drop_column('questions', 'difficulty')
    op.drop_column('questions', 'explanation')
    # ### end Alembic commands ###
